x-env: &env
  YTDLPY_SOCKET_PATH: '/tmp/jukebox/ytdlpy.sock'

services:
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      <<: *env
      MAX_CONCURRENT_WORKER_PER_POOL: 2
      MAX_TASK_QUEUE_SIZE: 4
      LOG_LEVEL: debug
    volumes:
      - shared_tmp:/tmp
    depends_on:
      - ytdlpy

  ytdlpy:
    build:
      context: ./ytdlpy
      dockerfile: Dockerfile
    environment:
      <<: *env
      YTDLPY_SOCKET_DIR: '/tmp/jukebox'
      YTDLPY_MAX_CONCURRENT_DL: 4
    volumes:
      - shared_tmp:/tmp

  nginx:
    image: nginx:alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/certs:/etc/nginx/certs
    depends_on:
      - web
      - ytdlpy

volumes:
  shared_tmp:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
