x-env: &env
  YTDLPY_SOCKET_PATH: '/tmp/jukebox/ytdlpy.sock'

services:
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      <<: *env
      MAX_CONCURRENT_WORKER_PER_POOL: 2
      MAX_TASK_QUEUE_SIZE: 4
    volumes:
      - shared_tmp:/tmp
  ytdlpy:
    build:
      context: ./ytdlpy
      dockerfile: Dockerfile
    environment:
      <<: *env
      YTDLPY_SOCKET_DIR: '/tmp/jukebox'
      YTDLPY_MAX_CONCURRENT_DL: 4
    volumes:
      - shared_tmp:/tmp

volumes:
  shared_tmp:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
