x-env: &env
  YTDLPY_SOCKET_PATH: '/tmp/jukebox/ytdlpy.sock'
  YTDLPY_SOCKET_DIR: '/tmp/jukebox'

services:
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment: *env
    volumes:
      - shared_tmp:/tmp
  ytdlpy:
    build:
      context: ./ytdlpy
      dockerfile: Dockerfile
    ports:
      - 5000:5000 # debug
    environment: *env
    volumes:
      - shared_tmp:/tmp

volumes:
  shared_tmp:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
